mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.database.restaurant.mybatis.entity
server:
  port: 8080
default_pic_url: https://www.manpingou.com/uploads/allimg/180918/25-1P91Q1235E15.jpg
file:
  path: E:/desktop/files/school-work/DataBase/Restaurant/files/
chef_email: 2454787428@qq.com
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: Restaurant
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    name: defaultDataSource
    password: root
    username: root
  mail:
    default-encoding: UTF-8
    host: smtp.yandex.com
    password: spmUsst0001
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    protocol: smtp
    test-connection: false
    username: spm.usst@yandex.com