mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.database.restaurant.mybatis.entity
server:
  port: 8080
default_pic_url: https://www.manpingou.com/uploads/allimg/180918/25-1P91Q1235E15.jpg
spring:
  application:
    name: Restaurant
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    name: defaultDataSource
    password: root
    username: root
  mvc:
    converters:
      preferred-json-mapper: gson